### ISSUE TITLE
Facebook Test Users

### ISSUE THREAD

**Issue by brettpthomas** [thomasmeagher/Tindergram#1]
Perhaps a naive question - wondering if it's possible to login credentials for a Facebook test user to the README. Or does everyone that wants to try this out this have to register the app separately and create their own test users?

**Comment by tmm** [comment]
Facebook doesn't like test accounts, but you are welcome to use your own FB account to test the app! I created eight test profiles that you can swipe through, etc.

Will update the README and code to make it clear how to test everything out.
