### ISSUE TITLE
Chat not working correctly

### ISSUE THREAD

**Issue by tobeee** [thomasmeagher/Tindergram#2]
Hi guys,

Anyone else having difficulty with the chat not working correctly? I've tried it out on two phones - the messages send from both, but the responses never appear on the other client.

I've checked in Firebase, and both sets are being created - when I go to the chat again it loads all of one persons previous messages but doesn't load the other at all. I assume its something to do with the matching but was wondering if anyone else has encountered anything similar?

**Comment by tmm** [comment]
Hey @tobeee! Working on another project right now – will take a look when I get a chance.

Stay persistent, and update if you find it. FYI, Parse will need to be refactored out at some point too.

**Comment by tobeee** [comment]
Hi Tom,

I did manage to fix it in the end. Will try and submit a PR asap

**Comment by alaxicsmith** [comment]
@tobeee how did you manage to fix this issue?

**Comment by tobeee** [comment]
In the MatchesTableVieController, try the below code. The issue was the current code created two separate Firebase channels for each chat match, instead of a single one, which both uses had access to. The below code uses a simple sort of both matches to each that both will use the same channel! Sorry if I've not explained it too well :) 
`  
    let vc = ChatViewController();

```
let match = matches[indexPath.row];

vc.title = match.user.name;

var chatmatch = [String]();
chatmatch.append(match.user.id);

chatmatch.append(PFUser.currentUser()!.objectId!);

var newcombinedID = chatmatch.sort().joinWithSeparator("-");
vc.matchID = newcombinedID;
```

`

**Comment by tobeee** [comment]
Wow github really messed up the formatting
